version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stream-backend
    ports:
      - "5000:5000"  # Local:Container
    volumes:
      - video_uploads:/app/uploads
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: stream-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: stream-admin
    ports:
      - "3001:3001" # Changed to 3001
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  video_uploads: